version: "3.8"
services:
  inside-db:
    image: postgres:13.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: insideDB